package sl_link;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nanopb.proto

// Protobuf Java Version: 3.25.9
public final class Nanopb {
  private Nanopb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(Nanopb.nanopbFileopt);
    registry.add(Nanopb.nanopbMsgopt);
    registry.add(Nanopb.nanopbEnumopt);
    registry.add(Nanopb.nanopb);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NanoPBOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NanoPBOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 max_size = 1;</code>
     * @return Whether the maxSize field is set.
     */
    boolean hasMaxSize();
    /**
     * <code>optional int32 max_size = 1;</code>
     * @return The maxSize.
     */
    int getMaxSize();

    /**
     * <code>optional int32 max_count = 2;</code>
     * @return Whether the maxCount field is set.
     */
    boolean hasMaxCount();
    /**
     * <code>optional int32 max_count = 2;</code>
     * @return The maxCount.
     */
    int getMaxCount();

    /**
     * <code>optional int32 max_length = 14;</code>
     * @return Whether the maxLength field is set.
     */
    boolean hasMaxLength();
    /**
     * <code>optional int32 max_length = 14;</code>
     * @return The maxLength.
     */
    int getMaxLength();
  }
  /**
   * Protobuf type {@code NanoPBOptions}
   */
  public static final class NanoPBOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NanoPBOptions)
      NanoPBOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NanoPBOptions.newBuilder() to construct.
    private NanoPBOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NanoPBOptions() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new NanoPBOptions();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Nanopb.internal_static_NanoPBOptions_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Nanopb.internal_static_NanoPBOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NanoPBOptions.class, Builder.class);
    }

    private int bitField0_;
    public static final int MAX_SIZE_FIELD_NUMBER = 1;
    private int maxSize_ = 0;
    /**
     * <code>optional int32 max_size = 1;</code>
     * @return Whether the maxSize field is set.
     */
    @Override
    public boolean hasMaxSize() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 max_size = 1;</code>
     * @return The maxSize.
     */
    @Override
    public int getMaxSize() {
      return maxSize_;
    }

    public static final int MAX_COUNT_FIELD_NUMBER = 2;
    private int maxCount_ = 0;
    /**
     * <code>optional int32 max_count = 2;</code>
     * @return Whether the maxCount field is set.
     */
    @Override
    public boolean hasMaxCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 max_count = 2;</code>
     * @return The maxCount.
     */
    @Override
    public int getMaxCount() {
      return maxCount_;
    }

    public static final int MAX_LENGTH_FIELD_NUMBER = 14;
    private int maxLength_ = 0;
    /**
     * <code>optional int32 max_length = 14;</code>
     * @return Whether the maxLength field is set.
     */
    @Override
    public boolean hasMaxLength() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 max_length = 14;</code>
     * @return The maxLength.
     */
    @Override
    public int getMaxLength() {
      return maxLength_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, maxSize_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, maxCount_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(14, maxLength_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, maxSize_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxCount_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, maxLength_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NanoPBOptions)) {
        return super.equals(obj);
      }
      NanoPBOptions other = (NanoPBOptions) obj;

      if (hasMaxSize() != other.hasMaxSize()) return false;
      if (hasMaxSize()) {
        if (getMaxSize()
            != other.getMaxSize()) return false;
      }
      if (hasMaxCount() != other.hasMaxCount()) return false;
      if (hasMaxCount()) {
        if (getMaxCount()
            != other.getMaxCount()) return false;
      }
      if (hasMaxLength() != other.hasMaxLength()) return false;
      if (hasMaxLength()) {
        if (getMaxLength()
            != other.getMaxLength()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMaxSize()) {
        hash = (37 * hash) + MAX_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getMaxSize();
      }
      if (hasMaxCount()) {
        hash = (37 * hash) + MAX_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getMaxCount();
      }
      if (hasMaxLength()) {
        hash = (37 * hash) + MAX_LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getMaxLength();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NanoPBOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NanoPBOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NanoPBOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NanoPBOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NanoPBOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NanoPBOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NanoPBOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NanoPBOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static NanoPBOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static NanoPBOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NanoPBOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NanoPBOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NanoPBOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NanoPBOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NanoPBOptions)
        NanoPBOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Nanopb.internal_static_NanoPBOptions_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Nanopb.internal_static_NanoPBOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NanoPBOptions.class, Builder.class);
      }

      // Construct using Nanopb.NanoPBOptions.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        maxSize_ = 0;
        maxCount_ = 0;
        maxLength_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Nanopb.internal_static_NanoPBOptions_descriptor;
      }

      @Override
      public NanoPBOptions getDefaultInstanceForType() {
        return NanoPBOptions.getDefaultInstance();
      }

      @Override
      public NanoPBOptions build() {
        NanoPBOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public NanoPBOptions buildPartial() {
        NanoPBOptions result = new NanoPBOptions(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(NanoPBOptions result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.maxSize_ = maxSize_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.maxCount_ = maxCount_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.maxLength_ = maxLength_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NanoPBOptions) {
          return mergeFrom((NanoPBOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NanoPBOptions other) {
        if (other == NanoPBOptions.getDefaultInstance()) return this;
        if (other.hasMaxSize()) {
          setMaxSize(other.getMaxSize());
        }
        if (other.hasMaxCount()) {
          setMaxCount(other.getMaxCount());
        }
        if (other.hasMaxLength()) {
          setMaxLength(other.getMaxLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                maxSize_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                maxCount_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 112: {
                maxLength_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 112
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int maxSize_ ;
      /**
       * <code>optional int32 max_size = 1;</code>
       * @return Whether the maxSize field is set.
       */
      @Override
      public boolean hasMaxSize() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 max_size = 1;</code>
       * @return The maxSize.
       */
      @Override
      public int getMaxSize() {
        return maxSize_;
      }
      /**
       * <code>optional int32 max_size = 1;</code>
       * @param value The maxSize to set.
       * @return This builder for chaining.
       */
      public Builder setMaxSize(int value) {

        maxSize_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 max_size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        maxSize_ = 0;
        onChanged();
        return this;
      }

      private int maxCount_ ;
      /**
       * <code>optional int32 max_count = 2;</code>
       * @return Whether the maxCount field is set.
       */
      @Override
      public boolean hasMaxCount() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 max_count = 2;</code>
       * @return The maxCount.
       */
      @Override
      public int getMaxCount() {
        return maxCount_;
      }
      /**
       * <code>optional int32 max_count = 2;</code>
       * @param value The maxCount to set.
       * @return This builder for chaining.
       */
      public Builder setMaxCount(int value) {

        maxCount_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 max_count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxCount_ = 0;
        onChanged();
        return this;
      }

      private int maxLength_ ;
      /**
       * <code>optional int32 max_length = 14;</code>
       * @return Whether the maxLength field is set.
       */
      @Override
      public boolean hasMaxLength() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 max_length = 14;</code>
       * @return The maxLength.
       */
      @Override
      public int getMaxLength() {
        return maxLength_;
      }
      /**
       * <code>optional int32 max_length = 14;</code>
       * @param value The maxLength to set.
       * @return This builder for chaining.
       */
      public Builder setMaxLength(int value) {

        maxLength_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 max_length = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxLength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxLength_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NanoPBOptions)
    }

    // @@protoc_insertion_point(class_scope:NanoPBOptions)
    private static final NanoPBOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NanoPBOptions();
    }

    public static NanoPBOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<NanoPBOptions>
        PARSER = new com.google.protobuf.AbstractParser<NanoPBOptions>() {
      @Override
      public NanoPBOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NanoPBOptions> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NanoPBOptions> getParserForType() {
      return PARSER;
    }

    @Override
    public NanoPBOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NANOPB_FILEOPT_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      NanoPBOptions> nanopbFileopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        NanoPBOptions.class,
        NanoPBOptions.getDefaultInstance());
  public static final int NANOPB_MSGOPT_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      NanoPBOptions> nanopbMsgopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        NanoPBOptions.class,
        NanoPBOptions.getDefaultInstance());
  public static final int NANOPB_ENUMOPT_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      NanoPBOptions> nanopbEnumopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        NanoPBOptions.class,
        NanoPBOptions.getDefaultInstance());
  public static final int NANOPB_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      NanoPBOptions> nanopb = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        NanoPBOptions.class,
        NanoPBOptions.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NanoPBOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NanoPBOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014nanopb.proto\032 google/protobuf/descript" +
      "or.proto\"H\n\rNanoPBOptions\022\020\n\010max_size\030\001 " +
      "\001(\005\022\021\n\tmax_count\030\002 \001(\005\022\022\n\nmax_length\030\016 \001" +
      "(\005:E\n\016nanopb_fileopt\022\034.google.protobuf.F" +
      "ileOptions\030\362\007 \001(\0132\016.NanoPBOptions:G\n\rnan" +
      "opb_msgopt\022\037.google.protobuf.MessageOpti" +
      "ons\030\362\007 \001(\0132\016.NanoPBOptions:E\n\016nanopb_enu" +
      "mopt\022\034.google.protobuf.EnumOptions\030\362\007 \001(" +
      "\0132\016.NanoPBOptions:>\n\006nanopb\022\035.google.pro" +
      "tobuf.FieldOptions\030\362\007 \001(\0132\016.NanoPBOption" +
      "s"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_NanoPBOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NanoPBOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NanoPBOptions_descriptor,
        new String[] { "MaxSize", "MaxCount", "MaxLength", });
    nanopbFileopt.internalInit(descriptor.getExtensions().get(0));
    nanopbMsgopt.internalInit(descriptor.getExtensions().get(1));
    nanopbEnumopt.internalInit(descriptor.getExtensions().get(2));
    nanopb.internalInit(descriptor.getExtensions().get(3));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
